// Visual constants
export const CRESCENT_CONFIG = {
  MOON_BASE_SCALE: 0.95,
  INNER_CIRCLE_SCALE: 0.92,
  OFFSET_DISTANCE: 0.03,
  MOON_OPACITY: 0.15,
  INITIAL_ANGLE_DEG: 45,
} as const;

export const ANIMATION_DURATIONS = {
  ENTER_EXIT: 300,
  RADIUS_TRANSITION: 300,
  COLOR_TRANSITION: 200,
} as const;

export const SIMULATION_CONFIG = {
  COLLISION_PADDING: 2,
  CENTER_STRENGTH: 0.05,
  CHARGE_STRENGTH: -30,
  BOUNDARY_PADDING: 10,
  ALPHA_DECAY: 0.001,
  VELOCITY_DECAY: 0.8,
  CRESCENT_MIN_DISTANCE: 0.1,
  CRESCENT_SPEED_FACTOR: 0.02,
  CRESCENT_MAX_SPEED: 0.3,
} as const;
